### ISSUE TITLE
výběr transformace

### ISSUE THREAD

**Issue by kalab-oto** [GISMentors/qgis-zacatecnik#15]
Přidat do materiálů popis okna výběru transformace 5514 to wgs, (při přidávání 5514 vrstvy do projektu 4326 a naopak)

**Comment by AlzbetaGardonova** [comment]
@kalab-oto  myslíš přiřazení souř. sys.?

**Comment by kalab-oto** [comment]
Ne-e, myslím toto:
![Snímek z 2019-11-02 17-25-44](https://user-images.githubusercontent.com/13303725/68073956-f098a200-fd95-11e9-88ec-78c46f2ccfd6.png)

Což se asi ukáže pokud transformace není nastavená, možná po nové instalaci

**Comment by AlzbetaGardonova** [comment]
ok, dík, tohle nepoužívám (nemám povoleno), tak mě to nenapadlo

**Comment by kalab-oto** [comment]
:) no  mě se to tam začalo ukazovat až teď myslím, ono to stačí nastavit jednou, jako zvolit jednu transformaci :) Ale bylo by to dobrý to tam mít, protože když si někdo nainstaluje QGIS a začne míchat WGS a S-JTSK tak mu to tam vyskočí

**Comment by kalab-oto** [comment]
Martin navrhuje 1623 (http://epsg.io/5514-1623)
viz https://gismentors.slack.com/archives/CAJNES81L/p1574355799004500

**Comment by AlzbetaGardonova** [comment]
přidáno sem: https://training.gismentors.eu/qgis-zacatecnik/intro/import_export.html#transformace
