### ISSUE TITLE
pripravit data v /mnt/repository

### ISSUE THREAD

**Issue by landam** [GISMentors/qgis-zacatecnik#3]

**Comment by AlzbetaGardonova** [comment]
## Zatím potřebuju:

mapový výstup:
- ochrana_uzemi velkoplosna_uzemi
- ruian kraje

předpokládám, že Oto bude říkat vektory, tak já bych dala rastry  tedy dmt

přijde mi, že radši to ukazovat na menším množství dat, než na moc velkém - základy se dají ukázat na čemkoli

**Comment by kalab-oto** [comment]
Souhlasím, já těch dat taky moc nepotřebuju (kdyžtak ještě doplním) 

zatím navíc jen:
- osm - silnice (stačí typ 1-3) 
- ruian - státy

Potom budu potřebovat ještě  2 csv tabulky, jednu na import dat a druhou na připojení - ty bych poslal

Jo ten výklad musíme nějak poskládat tak aby to šlo rozumně a abysme se střídaly po těch blocích.

**Comment by lfurtkevicova** [comment]
Ja som využila:
- dmt.tiff 
- osm - silnice, pozarni stanice
- ruian - obce

a ešte by sa asi zišla nejaká vrstva *.dxf (použila som praha.dxf a stiahla som ju [TU](https://cadmapper.com/#metro))  .. ale nie je to nič hrozne potrebné

**Comment by kalab-oto** [comment]
prosím ještě přidat
- ochrana_uzemi maloplosna_uzemi
- a tabulky:
  [export.txt](https://github.com/GISMentors/qgis-zacatecnik/files/39270/export.txt)
  [xy_data.txt](https://github.com/GISMentors/qgis-zacatecnik/files/39271/xy_data.txt)
  (koncovka bude .csv, se jde nahrát jen .txt)
