### ISSUE TITLE
S-JTSK a podivne souradnice

### ISSUE THREAD

**Issue by landam** [GISMentors/qgis-zacatecnik#4]
V souboru qgis_pluginy je uvedeno:

```
S-JTSK (Greenwich) Krovak a S-JTSK (Greenwich) Krovak East North. Ikona askcorcopy umožňuje souřadnice kopírovat do schránky v podobě čtyř hodnot (pro obr. 7 by to bylo 4494520.158,-2880372.147, 4746310.700,2931421.671).
```

Opravdu jde o S-JTSK?

**Comment by lfurtkevicova** [comment]
ty kokso, to ti teraz asi nepoviem.. ja uz vlastne spim .. je to jedno, islo iba o to, ukazat, ze to ukazuje dvojake suradnice.. akebo tam bol aj obrazok co? dobre idem sa pozriet

Odoslané z iPadu

Dňa 20.11.2015, o 0:27, Martin Landa notifications@github.com napísal:
